name: sample action file - dispatch
on:
  workflow_dispatch
      
jobs:
  Helloworld:
    runs-on : ubuntu-latest
    steps:
      - name: first action
        run: echo "Hello World from dispatch branch"

  checkout:
    runs-on : ubuntu-latest
    steps:
        
      - name: checkout
        uses: actions/checkout@v4
        

      - name: print file content
        run: echo "Hello World from main branch"
             cat sample.txt
